x = input('Digite algo: ')
print('A variavel {} será analisada'.format(x))
print('Seu tipo é', type(x))
print('É numérico:', x.isnumeric())
print('É composto de letras:', x.isalpha())
print('É composto de espaços', x.isspace())
print('É formado de numeros e letras:', x.isalnum())
print('É composto de maiusculas:', x.isupper())
print('É composto de minusculas:' , x.islower())
print('É feito de maiusculas e minusculas:', x.istitle())
